[package]
authors = ["Vitaly Domnikov <oss@vitaly.codes>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "Peripheral access API for STM32G0 series microcontrollers"
documentation = "https://docs.rs/stm32g0xx-hal"
edition = "2018"
keywords = ["arm", "cortex-m", "stm32g0xx", "hal"]
license = "MIT/Apache-2.0"
name = "stm32g0xx-hal"
readme = "README.md"
repository = "https://github.com/stm32-rs/stm32g0xx-hal"
version = "0.0.5"

[dependencies]
cortex-m = "0.6.1"
nb = "0.1.1"
stm32g0 = "0.9.0"
as-slice = "0.2.0"

[dependencies.bare-metal]
features = ["const-fn"]
version = "0.2.5"

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.3"

[dependencies.void]
default-features = false
version = "1.0.2"

[dev-dependencies]
cortex-m-rt = "0.6.10"
cortex-m-rtfm = "0.4.2"
cortex-m-semihosting = "0.3.5"
panic-halt = "0.2.0"

[features]
default = ["rt", "stm32g07x"]
rt = ["stm32g0/rt"]
stm32g07x = ["stm32g0/stm32g07x"]
stm32g030 = ["stm32g0/stm32g030"]
stm32g031 = ["stm32g0/stm32g031"]
stm32g041 = ["stm32g0/stm32g041"]
stm32g081 = ["stm32g0/stm32g081"]

[profile.dev]
codegen-units = 1
debug = true
incremental = false
lto = false

[profile.release]
debug = false
codegen-units = 1
incremental = false
lto = true
