[package]
edition = "2018"
authors = ["Vitaly Domnikov <oss@vitaly.codes>"]
categories = [
    "embedded",
    "hardware-support",
    "no-std",
]
description = "Peripheral access API for STM32G0 series microcontrollers"
documentation = "https://docs.rs/stm32g0xx-hal"
keywords = [
    "arm",
    "cortex-m",
    "stm32g0xx",
    "hal",
]
license = "MIT/Apache-2.0"
name = "stm32g0xx-hal"
readme = "README.md"
repository = "https://github.com/stm32-rs/stm32g0xx-hal"
version = "0.0.2"

[dependencies]
cortex-m = "0.5.8"
cortex-m-semihosting = "0.3.2"
nb = "0.1.1"
stm32g0 = "0.6.0"
bare-metal = { version = "0.2.4", features = ["const-fn"] }
embedded-hal = { version = "0.2.2", features = ["unproven"] }
void = { version = "1.0.2", default-features = false }

[dev-dependencies]
cortex-m-rt = "0.6.7"
panic-semihosting = "0.5.1"
cortex-m-rtfm = "0.4.2"

[features]
default = ["rt", "stm32g071"]
rt = ["stm32g0/rt"]
stm32g070 = ["stm32g0/stm32g0x0"]
stm32g071 = ["stm32g0/stm32g0x1"]
stm32g081 = ["stm32g0/stm32g0x1"]

[profile.dev]
codegen-units = 1
incremental = false

[profile.release]
incremental = false
codegen-units = 1
debug = true
lto = true
